apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
data:
  # Backend Configuration
  PORT: "5000"
  NODE_ENV: "production"
  
  # Frontend Configuration
  VITE_API_URL: "http://backend-service:5000"
  
  # Database Configuration (MongoDB Atlas - Cloud hosted)
  DB_NAME: "test"
