apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
stringData:
  # MongoDB Atlas Connection String
  # IMPORTANT: Replace this with your actual MongoDB URI in production
  MONGO_URI: "mongodb+srv://muhammadowais87:12344321@cluster0.weif8lt.mongodb.net/test?appName=Cluster0"
  
  # JWT Secret for authentication
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  
  # Admin JWT Secret
  ADMIN_JWT_SECRET: "your-admin-jwt-secret-change-in-production"
